inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'expressir.gemspec'
    - 'tmp/**/*'
    - 'pkg/**/*'
    - 'exe/format-test'
    - 'lib/expressir/express/**/*'
    - 'lib/expressir/model/**/*'

Layout/LineLength:
  Max: 160
