require:
  - rubocop-performance

inherit_from:
  - https://raw.githubusercontent.com/riboseinc/oss-guides/master/ci/rubocop.yml
  - .rubocop_todo.yml

Naming/VariableName:
  Exclude:
  - lib/expressir/express/visitor.rb
Layout/LineLength:
  Max: 160
AllCops:
  TargetRubyVersion: 2.7
