= Expressir: EXPRESS in Ruby

image:https://github.com/metanorma/expressir/workflows/ubuntu/badge.svg[GitHub Workflow Status (master), link="https://github.com/metanorma/expressir/actions?workflow=ubuntu"]

== Purpose

Expressir ("`EXPRESS in Ruby`") is a Ruby parser for EXPRESS and
a set of Ruby tools for accessing ISO EXPRESS data models.

It accepts the input of the following format:

* EXPRESS data modelling language (ISO 10303-11:2007)

* EXPRESS data modelling language in XML (STEPmod)

* EXPRESS XML (ISO 10303-28:2007)
"`Industrial automation systems and integration — Product data representation and exchange — Part 28: Implementation methods: XML representations of EXPRESS schemas and data, using XML schemas`")

It outputs the following formats:

* W3C OWL
* OMG SysML (XMI 2.1, XMI 2.5)
* OMG UML 2 (XMI 2.1)
* OMG UML 2 for Eclipse (XMI 2.1)


== Installation

Add this line to your application's `Gemfile`:

[source, sh]
----
gem "expressir"
----

And then execute:

[source, sh]
----
$ bundle install
----

Or install it yourself as:

[source, sh]
----
$ gem install expressir
----

== Usage

This gem ships with a CLI tool. To check what's available you can simply run
the script directly from `exe/expressir`, by default it will display some usage
instructions.

[source, sh]
----
./exe/expressir

Commands:
  expressir help [COMMAND]  # Describe available commands or one specific command
  expressir version         # The Expressir Version
----

== Development

We are following Sandi Metz's Rules for this gem, you can read
the http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers[description of the rules here] All new code should follow these rules.
If you make changes in a pre-existing file that violates these rules you should
fix the violations as part of your contribution.

=== Setup

Clone the repository.

[source, sh]
----
git clone https://github.com/metanorma/expressir
----

Setup your environment.

[source, sh]
----
bin/setup
----

Run the test suite

[source, sh]
----
bin/rspec
----

== Contributing

First, thank you for contributing! We love pull requests from everyone. By
participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an unlimited
number of non exclusive licenses or sub-licenses to third parties, under the
copyright covering the contribution to use the contribution by all means.

Here are a few technical guidelines to follow:

* Open an https://github.com/metanorma/expressir/issues[issues] to discuss a new
  feature.
* Write tests to support your new feature.
* Make sure the entire test suite passes locally and on CI.
* Open a Pull Request.
* https://github.com/thoughtbot/guides/tree/master/protocol/git#write-a-feature[Squash your commits] after receiving feedback.
* Party!


== License

Expressir is distributed under the BSD 2-clause license.

Expressir is built on code originally from the NIST Reeper project.

The https://www.nist.gov/services-resources/software/reeper[NIST Reeper license]
is reproduced below:

[quote]
____
This software was funded by NIST and developed by EuroSTEP.
Pursuant to title 17 Section 105 of the United States Code this
software is not subject to copyright protection and is in the public
domain.

We would appreciate acknowledgment if the software is used. Links to
non-Federal Government Web sites do not imply NIST endorsement of any
particular product, service, organization, company, information
provider, or content.
____


== Credits

Expressir is created using the structure and examples provided by
the NIST Reeper software on https://sourceforge.net/p/reeper/[Sourceforge].



