= Reeper

image:https://github.com/metanorma/reeper/workflows/ubuntu/badge.svg[GitHub Workflow Status (master), link="https://github.com/metanorma/reeper/actions?workflow=ubuntu"]

WARNING: This is a fork of the NIST Reeper software originally at
https://sourceforge.net/p/reeper/[Sourceforge]. It is forked for
potential improvements.

The mirrored branch is located at the
https://github.com/metanorma/reeper/releases/tag/v0.1[`pre-release` tag]

== Purpose

Reeper is a set of Ruby tools for harvesting ISO EXPRESS data models.

See https://www.nist.gov/services-resources/software/reeper[NIST's Reeper page] for further details.

It accepts the input of the following format:

* EXPRESS XML (ISO 10303-28:2007
"`Industrial automation systems and integration — Product data representation and exchange — Part 28: Implementation methods: XML representations of EXPRESS schemas and data, using XML schemas`")

NOTE: Reeper does not accept ASCII EXPRESS (ISO 10303-11) input today.
Something may have to be done about this.

And outputs the following formats:

* W3C OWL
* OMG SysML (XMI 2.1, XMI 2.5)
* OMG UML 2 (XMI 2.1)
* OMG UML 2 for Eclipse (XMI 2.1)

== Origin of name

Reeper was likely to have been named by Eurostep as the "`Ruby
version`" of their `eep` parser which stood for `Eurostep EXPRESS
Parser`.
The origin of the suffix `er` is so far unknown.

== License

Original license described at the
https://www.nist.gov/services-resources/software/reeper[NIST Reeper page]
and reproduced below.

This software was funded by NIST and developed by EuroSTEP.
Pursuant to title 17 Section 105 of the United States Code this
software is not subject to copyright protection and is in the public
domain.

We would appreciate acknowledgment if the software is used. Links to
non-Federal Government Web sites do not imply NIST endorsement of any
particular product, service, organization, company, information
provider, or content.


== Installation

Add this line to your application's `Gemfile`:

[source, sh]
----
gem "reeper"
----

And then execute:

[source, sh]
----
$ bundle install
----

Or install it yourself as:

[source, sh]
----
$ gem install reeper
----

== Usage

TODO: Usages insruction will follow soon.


This gem ships with a CLI tool, to check what's available you can simply run
the script directly from `exe/reeper`, by default it will display some usages
instructions.

[source, sh]
----
./exe/reeper

Commands:
  reeper help [COMMAND]  # Describe available commands or one specific command
  reeper version         # The Reeper Version
----

== Development

We are following Sandi Metz's Rules for this gem, you can read
the http://robots.thoughtbot.com/post/50655960596/sandi-metz-rules-for-developers[description of the rules here] All new code should follow these rules.
If you make changes in a pre-existing file that violates these rules you should
fix the violations as part of your contribution.

=== Setup

Clone the repository.

[source, sh]
----
git clone https://github.com/metanorma/reeper
----

Setup your environment.

[source, sh]
----
bin/setup
----

Run the test suite

[source, sh]
----
bin/rspec
----

== Contributing

First, thank you for contributing! We love pull requests from everyone. By
participating in this project, you hereby grant
https://www.ribose.com[Ribose Inc.] the right to grant or transfer an unlimited
number of non exclusive licenses or sub-licenses to third parties, under the
copyright covering the contribution to use the contribution by all means.

Here are a few technical guidelines to follow:

* Open an https://github.com/metanorma/reeper/issues[issues] to discuss a new
  feature.
* Write tests to support your new feature.
* Make sure the entire test suite passes locally and on CI.
* Open a Pull Request.
* https://github.com/thoughtbot/guides/tree/master/protocol/git#write-a-feature[Squash your commits] after receiving feedback.
* Party!

== Credits

This library was initialially developed by
https://www.nist.gov/services-resources/software/reeper[NIST], and then forked
by https://www.ribose.com[Ribose Inc] for futher imporvements, pleast check the
https://www.nist.gov/services-resources/software/reeper[NIST] for details
licensing and futher usages.
