SCHEMA syntax_schema '{ISO standard 10303 part(41) object(1) version(8)}';

USE FROM contract_schema;
USE FROM contract_schema
  (contract);
USE FROM contract_schema
  (contract,
   contract2);
USE FROM contract_schema
  (contract AS contract2);
REFERENCE FROM contract_schema;
REFERENCE FROM contract_schema
  (contract);
REFERENCE FROM contract_schema
  (contract,
   contract2);
REFERENCE FROM contract_schema
  (contract AS contract2);