#!/usr/bin/env ruby

require "yaml"
require "expressir"
require "expressir/express/formatter"
require "expressir/express/schema_head_formatter"
require "expressir/express/hyperlink_formatter"

exp_files = ARGV

repository = Expressir::Express::Parser.from_files(exp_files)
repository.schemas.each do |schema|
  puts schema.to_s(no_remarks: true)
end
