name: alpine

on:
  push:
#    branches: [ master, main ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/rake.yml
      - .github/workflows/release.yml
  pull_request:
  workflow_dispatch:

jobs:
  pack-ruby:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Build gem without native extension
        run: gem build expressir.gemspec

      - name: Package gem without native extension
        uses: actions/upload-artifact@v2
        with:
          name: pkg-ruby
          path: expressir-*.gem

  pack-linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Build gem with x86_64-linux native extension
        run: bundle exec rake gem:x86_64-linux

      - name: Package gem with native extension
        uses: actions/upload-artifact@v2
        with:
          name: pkg-x86_64-linux
          path: pkg/expressir-*.gem

  verify-ruby-platform:
    runs-on: ubuntu-latest
    needs: pack-ruby
    container:
      image: alpine:3.15

    steps:
      - name: Install packages
        run: apk --no-cache --upgrade add bash build-base cmake git ruby-dev

      - run: git config --global --add safe.directory "$(pwd)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bundler
        run: gem install bundler

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Download packaged gem
        uses: actions/download-artifact@v2
        with:
         name: pkg-ruby
         path: pkg

      - name: Install gem
        run: gem install -l pkg/expressir-*.gem

      - name: Verify
        run: |
          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
          ruby bin/rspec
          cat .rspec_status || echo ".rspec_status was not found"

  verify-gcompat:
    runs-on: ubuntu-latest
    needs: pack-linux
    continue-on-error: true
    container:
      image: alpine:3.15

    steps:
      - name: Install packages
        run: apk --no-cache --upgrade add bash build-base cmake gcompat git ruby-dev

      - run: git config --global --add safe.directory "$(pwd)"

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install bundler
        run: gem install bundler

      - name: Bundle
        run: bundle install --jobs 4 --retry 3

      - name: Download packaged gem
        uses: actions/download-artifact@v2
        with:
         name: pkg-x86_64-linux
         path: pkg

      - name: Install gem
        run: gem install -l pkg/expressir-*.gem

      - name: Verify
        run: |
          cd $(ruby -e "puts RbConfig::TOPDIR + '\/lib\/ruby\/gems\/' + RbConfig::CONFIG['ruby_version'] + '\/gems\/expressir*'")
          ruby bin/rspec
          cat .rspec_status || echo ".rspec_status was not found"
